apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: test-admission
  labels:
    app: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - name: httpbin
          image: scrapinghub/httpbin:latest
          command:
            - sleep
            - "3600"
          resources:
            requests:
              cpu: 0.1
              memory: 200