#v1beta1 will be mutated to v1 when k8s version is > 1.15
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-quarkus-admission-controller
webhooks:
  - name: validating.quarkus-admission-controller.sevel.eu
    rules:
      - apiGroups:
          - "apps"
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - deployments
    namespaceSelector:
      matchLabels:
        admission: enabled
    clientConfig:
      service:
        namespace: admission
        name: quarkus-admission-controller
        path: /validate
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJd01Ea3lNekUxTURneU4xb1hEVE13TURreU1qRTFNRGd5TjFvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHJlCnFoVFNPTE5vaDQxNjhERHo0WGZxMVlJamYvMDVOcEVBNnhOSXhjSzhRWTJnUys2RlNuUzZwS21NRXZ0WElLV0YKUS9NYnF1T3VBNktwbEdwT2NJcTVtR2tLN2M1Q2JiTy9DUVpoSklMeHUxeHEwMndleFBrWTIxbzhjcFZXRUZQaQphcnlUQlp3TWhEK040ZEZkR1hJUFd0Tzg5dS9XeHByQmlvc0pvRW0zOEp0K05KN2Y3VHRZUjdNTzFUVUxBcEdXCldrdzc1Y0g1ajAzcVUrUk1Jcm1VditCeTd5VkZQV2QyWWp6UjVFWktXV2FWZ0pTRFphTHkxeEtqRkFtUjl1NksKVTZqeE9DNEo5ZUdtekUyQndFNGJGMytlNks1VEcxQVdMREYvYjJCYXd2LzBCRk9rS2UrZ0hwWlN3ZUV1d1JYWgpLdUNxaEtLZFlRaTBidDNBNWY4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCeXl6ckNXbEpaeEY4V1pMaUxwdzVhWDRlVitwT1VDL0tSZGgzKzdGQ2p6YzhrNU1FVwo5ZGlXdlRBaGdtQkp1Y0ErblRKclY5azB4YXAzWmdBbGZUenpxSjdJSXMyUSt3UEJ6aVFzZ0RhRmhQaTRqNHpPCmZhNW8zY2dFMHdCZDlkVEZSMkNRVGNWL0V2dFViZzhqNFFydFkyRUgxZXVtaW9sNjRCK29hTVBXKzRQTm1nS0MKeVlWTWFEeDQwSmVJa1NHNXlVelR4aXErSkl4VjFwRkF0OWxOYTBiSWtDeW15bmdIekVCbE52enhIUE9lejh3TwpHMHgzNUhjdkdqd3QxaS9UOXBQNTA4RUpQK1NiNzFhend3Z3Bic1hEaGxZRjU2cDRCTFZXeGVNSFdIQTNIKzd4ClpRbzZLaXUyQW04OXVnbXI2RGowKzQwVU5ReHlUUGJEZXlnWQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    failurePolicy: Ignore
